package com.cms.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cms_attachment", "id", Attachment.class);
		arp.addMapping("cms_comment", "id", Comment.class);
		arp.addMapping("cms_content", "id", Content.class);
		arp.addMapping("cms_mapping", "id", Mapping.class);
		arp.addMapping("cms_metadata", "id", Metadata.class);
		arp.addMapping("cms_option", "id", Option.class);
		arp.addMapping("cms_taxonomy", "id", Taxonomy.class);
		arp.addMapping("cms_user", "id", User.class);
	}
}

