package com.cms.model;

import com.cms.model.base.BaseContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
	public static final Content dao = new Content().dao();
}
