package com.cms.model;

import com.cms.model.base.BaseMapping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mapping extends BaseMapping<Mapping> {
	public static final Mapping dao = new Mapping().dao();
}
