package com.cms.model;

import com.cms.model.base.BaseMetadata;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Metadata extends BaseMetadata<Metadata> {
	public static final Metadata dao = new Metadata().dao();
}
