package com.cms.model;

import com.cms.model.base.BaseOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Option extends BaseOption<Option> {
	public static final Option dao = new Option().dao();
}
