package com.cms.model;

import com.cms.model.base.BaseTaxonomy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Taxonomy extends BaseTaxonomy<Taxonomy> {
	public static final Taxonomy dao = new Taxonomy().dao();
}
