package com.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setParentId(java.math.BigInteger parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.math.BigInteger getParentId() {
		return get("parent_id");
	}

	public M setContentId(java.math.BigInteger contentId) {
		set("content_id", contentId);
		return (M)this;
	}

	public java.math.BigInteger getContentId() {
		return get("content_id");
	}

	public M setContentModule(java.lang.String contentModule) {
		set("content_module", contentModule);
		return (M)this;
	}

	public java.lang.String getContentModule() {
		return getStr("content_module");
	}

	public M setCommentCount(java.lang.Long commentCount) {
		set("comment_count", commentCount);
		return (M)this;
	}

	public java.lang.Long getCommentCount() {
		return getLong("comment_count");
	}

	public M setOrderNumber(java.lang.Long orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}

	public java.lang.Long getOrderNumber() {
		return getLong("order_number");
	}

	public M setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.math.BigInteger getUserId() {
		return get("user_id");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}

	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return getStr("text");
	}

	public M setAgent(java.lang.String agent) {
		set("agent", agent);
		return (M)this;
	}

	public java.lang.String getAgent() {
		return getStr("agent");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setSlug(java.lang.String slug) {
		set("slug", slug);
		return (M)this;
	}

	public java.lang.String getSlug() {
		return getStr("slug");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setVoteUp(java.lang.Long voteUp) {
		set("vote_up", voteUp);
		return (M)this;
	}

	public java.lang.Long getVoteUp() {
		return getLong("vote_up");
	}

	public M setVoteDown(java.lang.Long voteDown) {
		set("vote_down", voteDown);
		return (M)this;
	}

	public java.lang.Long getVoteDown() {
		return getLong("vote_down");
	}

	public M setFlag(java.lang.String flag) {
		set("flag", flag);
		return (M)this;
	}

	public java.lang.String getFlag() {
		return getStr("flag");
	}

	public M setLat(java.math.BigDecimal lat) {
		set("lat", lat);
		return (M)this;
	}

	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public M setLng(java.math.BigDecimal lng) {
		set("lng", lng);
		return (M)this;
	}

	public java.math.BigDecimal getLng() {
		return get("lng");
	}

}
