package com.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaxonomy<M extends BaseTaxonomy<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return getStr("text");
	}

	public M setSlug(java.lang.String slug) {
		set("slug", slug);
		return (M)this;
	}

	public java.lang.String getSlug() {
		return getStr("slug");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}

	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public M setContentModule(java.lang.String contentModule) {
		set("content_module", contentModule);
		return (M)this;
	}

	public java.lang.String getContentModule() {
		return getStr("content_module");
	}

	public M setContentCount(java.lang.Long contentCount) {
		set("content_count", contentCount);
		return (M)this;
	}

	public java.lang.Long getContentCount() {
		return getLong("content_count");
	}

	public M setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}

	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

	public M setParentId(java.math.BigInteger parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.math.BigInteger getParentId() {
		return get("parent_id");
	}

	public M setObjectId(java.math.BigInteger objectId) {
		set("object_id", objectId);
		return (M)this;
	}

	public java.math.BigInteger getObjectId() {
		return get("object_id");
	}

	public M setFlag(java.lang.String flag) {
		set("flag", flag);
		return (M)this;
	}

	public java.lang.String getFlag() {
		return getStr("flag");
	}

	public M setLat(java.math.BigDecimal lat) {
		set("lat", lat);
		return (M)this;
	}

	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public M setLng(java.math.BigDecimal lng) {
		set("lng", lng);
		return (M)this;
	}

	public java.math.BigDecimal getLng() {
		return get("lng");
	}

	public M setMetaKeywords(java.lang.String metaKeywords) {
		set("meta_keywords", metaKeywords);
		return (M)this;
	}

	public java.lang.String getMetaKeywords() {
		return getStr("meta_keywords");
	}

	public M setMetaDescription(java.lang.String metaDescription) {
		set("meta_description", metaDescription);
		return (M)this;
	}

	public java.lang.String getMetaDescription() {
		return getStr("meta_description");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
