package com.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAttachment<M extends BaseAttachment<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.math.BigInteger getUserId() {
		return get("user_id");
	}

	public M setContentId(java.math.BigInteger contentId) {
		set("content_id", contentId);
		return (M)this;
	}

	public java.math.BigInteger getContentId() {
		return get("content_id");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}

	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setMimeType(java.lang.String mimeType) {
		set("mime_type", mimeType);
		return (M)this;
	}

	public java.lang.String getMimeType() {
		return getStr("mime_type");
	}

	public M setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
		return (M)this;
	}

	public java.lang.String getSuffix() {
		return getStr("suffix");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setFlag(java.lang.String flag) {
		set("flag", flag);
		return (M)this;
	}

	public java.lang.String getFlag() {
		return getStr("flag");
	}

	public M setLat(java.math.BigDecimal lat) {
		set("lat", lat);
		return (M)this;
	}

	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public M setLng(java.math.BigDecimal lng) {
		set("lng", lng);
		return (M)this;
	}

	public java.math.BigDecimal getLng() {
		return get("lng");
	}

	public M setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}

	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
