package com.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return getStr("text");
	}

	public M setSummary(java.lang.String summary) {
		set("summary", summary);
		return (M)this;
	}

	public java.lang.String getSummary() {
		return getStr("summary");
	}

	public M setLinkTo(java.lang.String linkTo) {
		set("link_to", linkTo);
		return (M)this;
	}

	public java.lang.String getLinkTo() {
		return getStr("link_to");
	}

	public M setMarkdownEnable(java.lang.Boolean markdownEnable) {
		set("markdown_enable", markdownEnable);
		return (M)this;
	}

	public java.lang.Boolean getMarkdownEnable() {
		return get("markdown_enable");
	}

	public M setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
		return (M)this;
	}

	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

	public M setModule(java.lang.String module) {
		set("module", module);
		return (M)this;
	}

	public java.lang.String getModule() {
		return getStr("module");
	}

	public M setStyle(java.lang.String style) {
		set("style", style);
		return (M)this;
	}

	public java.lang.String getStyle() {
		return getStr("style");
	}

	public M setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.math.BigInteger getUserId() {
		return get("user_id");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}

	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setUserEmail(java.lang.String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}

	public java.lang.String getUserEmail() {
		return getStr("user_email");
	}

	public M setUserIp(java.lang.String userIp) {
		set("user_ip", userIp);
		return (M)this;
	}

	public java.lang.String getUserIp() {
		return getStr("user_ip");
	}

	public M setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
		return (M)this;
	}

	public java.lang.String getUserAgent() {
		return getStr("user_agent");
	}

	public M setParentId(java.math.BigInteger parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.math.BigInteger getParentId() {
		return get("parent_id");
	}

	public M setObjectId(java.math.BigInteger objectId) {
		set("object_id", objectId);
		return (M)this;
	}

	public java.math.BigInteger getObjectId() {
		return get("object_id");
	}

	public M setOrderNumber(java.lang.Long orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}

	public java.lang.Long getOrderNumber() {
		return getLong("order_number");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setVoteUp(java.lang.Long voteUp) {
		set("vote_up", voteUp);
		return (M)this;
	}

	public java.lang.Long getVoteUp() {
		return getLong("vote_up");
	}

	public M setVoteDown(java.lang.Long voteDown) {
		set("vote_down", voteDown);
		return (M)this;
	}

	public java.lang.Long getVoteDown() {
		return getLong("vote_down");
	}

	public M setRate(java.lang.Integer rate) {
		set("rate", rate);
		return (M)this;
	}

	public java.lang.Integer getRate() {
		return getInt("rate");
	}

	public M setRateCount(java.lang.Long rateCount) {
		set("rate_count", rateCount);
		return (M)this;
	}

	public java.lang.Long getRateCount() {
		return getLong("rate_count");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setCommentStatus(java.lang.String commentStatus) {
		set("comment_status", commentStatus);
		return (M)this;
	}

	public java.lang.String getCommentStatus() {
		return getStr("comment_status");
	}

	public M setCommentCount(java.lang.Long commentCount) {
		set("comment_count", commentCount);
		return (M)this;
	}

	public java.lang.Long getCommentCount() {
		return getLong("comment_count");
	}

	public M setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
		return (M)this;
	}

	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

	public M setViewCount(java.lang.Long viewCount) {
		set("view_count", viewCount);
		return (M)this;
	}

	public java.lang.Long getViewCount() {
		return getLong("view_count");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setModified(java.util.Date modified) {
		set("modified", modified);
		return (M)this;
	}

	public java.util.Date getModified() {
		return get("modified");
	}

	public M setSlug(java.lang.String slug) {
		set("slug", slug);
		return (M)this;
	}

	public java.lang.String getSlug() {
		return getStr("slug");
	}

	public M setFlag(java.lang.String flag) {
		set("flag", flag);
		return (M)this;
	}

	public java.lang.String getFlag() {
		return getStr("flag");
	}

	public M setLng(java.math.BigDecimal lng) {
		set("lng", lng);
		return (M)this;
	}

	public java.math.BigDecimal getLng() {
		return get("lng");
	}

	public M setLat(java.math.BigDecimal lat) {
		set("lat", lat);
		return (M)this;
	}

	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public M setMetaKeywords(java.lang.String metaKeywords) {
		set("meta_keywords", metaKeywords);
		return (M)this;
	}

	public java.lang.String getMetaKeywords() {
		return getStr("meta_keywords");
	}

	public M setMetaDescription(java.lang.String metaDescription) {
		set("meta_description", metaDescription);
		return (M)this;
	}

	public java.lang.String getMetaDescription() {
		return getStr("meta_description");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

}
