package com.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMapping<M extends BaseMapping<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setContentId(java.math.BigInteger contentId) {
		set("content_id", contentId);
		return (M)this;
	}

	public java.math.BigInteger getContentId() {
		return get("content_id");
	}

	public M setTaxonomyId(java.math.BigInteger taxonomyId) {
		set("taxonomy_id", taxonomyId);
		return (M)this;
	}

	public java.math.BigInteger getTaxonomyId() {
		return get("taxonomy_id");
	}

}
