package com.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMetadata<M extends BaseMetadata<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setMetaKey(java.lang.String metaKey) {
		set("meta_key", metaKey);
		return (M)this;
	}

	public java.lang.String getMetaKey() {
		return getStr("meta_key");
	}

	public M setMetaValue(java.lang.String metaValue) {
		set("meta_value", metaValue);
		return (M)this;
	}

	public java.lang.String getMetaValue() {
		return getStr("meta_value");
	}

	public M setObjectType(java.lang.String objectType) {
		set("object_type", objectType);
		return (M)this;
	}

	public java.lang.String getObjectType() {
		return getStr("object_type");
	}

	public M setObjectId(java.math.BigInteger objectId) {
		set("object_id", objectId);
		return (M)this;
	}

	public java.math.BigInteger getObjectId() {
		return get("object_id");
	}

}
